; nuke-filter.scm — grayscale + centered colored box logo, GIMP 3 batch
(define (nuke-filter infile outfile logofile)
  (let* ((image (car (gimp-file-load RUN-NONINTERACTIVE infile)))
         (imgw (car (gimp-image-get-width image)))
         (imgh (car (gimp-image-get-height image)))
         (drawable (car (gimp-image-flatten image))))
    (gimp-drawable-desaturate drawable 0)
    (let* ((logo (car (gimp-file-load-layer RUN-NONINTERACTIVE image logofile)))
           (logow (car (gimp-drawable-get-width logo)))
           (logoh (car (gimp-drawable-get-height logo)))
           (bw (inexact->exact (round (* 0.55 imgw))))
           (bh (inexact->exact (round (* bw (/ logoh logow))))))
      (gimp-image-insert-layer image logo 0 -1)
      (gimp-layer-scale logo bw bh TRUE)
      (gimp-layer-set-offsets logo
        (inexact->exact (round (/ (- imgw bw) 2)))
        (inexact->exact (round (/ (- imgh bh) 2))))
      (set! drawable (car (gimp-image-flatten image))))
    (gimp-file-save RUN-NONINTERACTIVE image outfile)
    (gimp-image-delete image)))
